# @package _global_

# config parameters
name: "" # default name for the experiment, "" means wandb will generate a unique name
group: "genetic_hp"
seed: 42 # seed for random number generator

# defaults
defaults:
  - dataloader: polarity
  - model: svm
  - sampler: genetic
  - _self_